server:
  port: 8111

spring:
  application:
      name: service-register
  security:
    filter:
      order: 100
      dispatcher-types: async,error,request
    user:
      name: admin
      password: 123456
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:123456${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 600000
