server:
  port: 8333

spring:
  data:
    mongodb:
      port: 27017
      database: test
      host: 127.0.0.1
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: bussniess
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:1111/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  kafka:
    producer:
      bootstrap-servers: 10.2.8.108:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
